### ISSUE TITLE
Problems with building pip package

### ISSUE THREAD

**Issue by n1ckelman** [dmlc/tensorboard#13]
Hello,
when I'm building tensorboard as pip package pip package, I receive:
`build_pip_package.sh: 20: build_pip_package.sh: Syntax error: "(" unexpected`

OS: Ubuntu 16.04
Python 2.7

**Comment by zihaolucky** [comment]
@n1ckelman Could you verify the problem? Any `Syntax error`?

**Comment by luoyetx** [comment]
I meet the same on Ubuntu 16.04 with Python2.7. By replace
```
sh bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh ../python/dist/
```
to
```
bash bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh ../python/dist/
```
in `install.sh` solve the problem. Basically, `sh` is linked to `dash` on Ubuntu, it seems different from `bash`.

More detail can be found [here](http://askubuntu.com/questions/141928/what-is-difference-between-bin-sh-and-bin-bash) and [here](http://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo).

**Comment by zihaolucky** [comment]
@luoyetx thank you! So changing `sh` to `bash` could work in `mac` and `linux` both? If so, we should update the script.

**Comment by luoyetx** [comment]
@zihaolucky I think it works as long as we use `bash`. I find the script file already uses `#!/usr/bin/env bash`, and it is executable, directly run `./bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh ../python/dist/`  should be more convenient.

**Comment by zihaolucky** [comment]
Good point, I would fix it, thank you.
