### ISSUE TITLE
cannot import name event_pb2

### ISSUE THREAD

**Issue by kernel8liang** [dmlc/tensorboard#15]
get an import error.

```
---> 23 from .src import event_pb2
     24 from .src import summary_pb2
     25 from .event_file_writer import EventFileWriter

ImportError: cannot import name event_pb2
```

**Comment by zihaolucky** [comment]
Did you compiled the protos and installed the Python package successfully? Please provide more info for me to reproduce.

**Comment by kernel8liang** [comment]
check around, found that files in ```tensorboard/python/tensorboard/src``` isn't copied to the site-packages/tensorboard. Manually copy these files, it works.

**Comment by zihaolucky** [comment]
@kernel8liang thanks for the feedback, let me check.

**Comment by zihaolucky** [comment]
could you tell me your system?

**Comment by zihaolucky** [comment]
do you install the package directly under the default python path?

**Comment by zihaolucky** [comment]
Please try the latest PyPI installation.

**Comment by JiamingSuen** [comment]
FYI: Met the same problem with custom built tensorboard wheel(since StringIO issue(#31) is still unfixed in 1.0.0a6). Fixed the same problem with https://github.com/dmlc/tensorboard/issues/15#issuecomment-277595345 .

**Comment by zihaolucky** [comment]
@JiamingSuen Please build from source, as we haven't finished the latest PyPI currently.

**Comment by murphypei** [comment]
Meet the same issue at the latest master branch.`tensorboard/python/tensorboard/src` is empty with only an empty` __init__.py` file

envs:
Ubuntu16.04
Python2.7
Bazel 0.6
