### ISSUE TITLE
No script named 'tensorboard'

### ISSUE THREAD

**Issue by kernel8liang** [dmlc/tensorboard#16]
after collecting logs, run command ```tensorboard --logdir=logs/```, get error below:

```
Traceback (most recent call last):
  File "/bin/tensorboard", line 4, in <module>
    __import__('pkg_resources').run_script('tensorboard', 'tensorboard')
  File "../lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "../lib/python2.7/site-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'tensorboard'
```

**Comment by kernel8liang** [comment]
directly run command ```lib/python2.7/site-packages/tensorboard/tensorboard```, it works.

**Comment by zihaolucky** [comment]
What's the output of `which tensorboard`, seems I've met this before, if the `tensorboard` binary exists, then the problem is the corresponding file path.

Could you help enhancing the script by create a PR after we solve these issues? Thank you!

**Comment by zihaolucky** [comment]
Open the `tensorboard` binary using vim or PyCharm, you might find:

```python
PYTHON_BINARY = '/Users/zihao.zzh/anaconda2/envs/tensorboard/bin/python'
```

The path should be same as the one in `tensorflow/tools/python_bin_path.sh`, and your default Python path.
