### ISSUE TITLE
Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2" while running installer.sh

### ISSUE THREAD

**Issue by themummy** [dmlc/tensorboard#17]
ubuntu@ip-172-31-38-221:~/git/tensorboard$ sh installer.sh
protoc tensorboard/src/*.proto --python_out=python/
tensorboard/src/event.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
make: *** [python/tensorboard/proto] Error 1

**Comment by zihaolucky** [comment]
You should use proto3. I guess your current protoc is version2.
