### ISSUE TITLE
StringIO issue when using python2 

### ISSUE THREAD

**Issue by hanzhanggit** [dmlc/tensorboard#31]
In the summary.py

"from six import StringIO" is not working for python 2.7. 
So I got this error, 
File "/home/hz138/anaconda2/lib/python2.7/site-packages/tensorboard/summary.py", line 186, in make_image
    output = StringIO.StringIO()
AttributeError: class StringIO has no attribute 'StringIO'

**Comment by zihaolucky** [comment]
Could you try change the `output = StringIO.StringIO()` to `output = StringIO()`?

**Comment by zihaolucky** [comment]
@hanzhanggit Do you install from source or via PyPI?

**Comment by hanzhanggit** [comment]
I install from using the following command:
pip install tensorboard. 
I have changed the source to be import StringIO instead of from six import StringIO to solve it locally(it might just work for python 2.7). But I think it is better to report this issue to fix it in the master branch.

**Comment by zihaolucky** [comment]
Agree. `six` is for both Python2 and Python3 compatible.

**Comment by hanzhanggit** [comment]
But if you want to keep using six for StringIO, at least we need to change the following line. 
output = StringIO.StringIO(). 
I just want to point out that currently the code does not work for python 2.7.

**Comment by zihaolucky** [comment]
let me make a fix later today. thank you.
