### ISSUE TITLE
Overwritten tensorboard of tensorflow

### ISSUE THREAD

**Issue by tienhv** [dmlc/tensorboard#33]
I installed this and it overwrote the tensorboard of tensorflow, could you rename it or do something to avoid this issues?

**Comment by zihaolucky** [comment]
You could install it in another env.

**Comment by wangg12** [comment]
Well，I don't think this is a good idea to break the tf's tb. Renamining maybe better.

**Comment by zihaolucky** [comment]
@tienhv @wangg12 I'm sorry to bring this inconvenience. 

We create this repo for those who want to use TensorBoard without TensorFlow, so we rewrite the logging part, it's a general and DL framework independent. The major work of this project is in this part, such as more types of summary.

For better maintenance, the rendering part remains almost same with the origin one so I can use bazel, reuse most of the code and scripts, so the name remains the same.
