### ISSUE TITLE
problem with installing tensorboard via virtualenv

### ISSUE THREAD

**Issue by taolei87** [dmlc/tensorboard#38]
Hi, this is a nice project and I'm trying to use it.

The issue I'm experiencing is probably related to #36. 

After I did `pip install tensorboard` in a virtual enviroment, tensorboard failed to launch. I got the following error:
```
Traceback (most recent call last):
  File "/Users/taolei/dlenv/bin/tensorboard", line 186, in <module>
    Main()
  File "/Users/taolei/dlenv/bin/tensorboard", line 135, in Main
    module_space = FindModuleSpace()
  File "/Users/taolei/dlenv/bin/tensorboard", line 83, in FindModuleSpace
    package_path = site.getsitepackages()
AttributeError: 'module' object has no attribute 'getsitepackages'
```

I tried to google about it and found that this is due to a open bug with Python 2.7 and vistualenv. See this:
[Python 2.7 isn't compatible with site.py. ](https://github.com/pypa/virtualenv/issues/355)
[issues with getsitepackages under a virtualenv](http://stackoverflow.com/questions/29888373/issues-with-getsitepackages-under-a-virtualenv)

I'm wondering if there is a possible fix (or a workaround).

Thanks!

**Comment by zihaolucky** [comment]
@taolei87 It's a known bug, I would fix it later. You could check here for temporary solution https://github.com/dmlc/tensorboard/issues/36.

**Comment by taolei87** [comment]
@zihaolucky What's the temporary solution?  I'm not using anaconda, but virtualenv in Mac OS. 
The error happens when the script calls `site.getsitepackages()`. 

Perhaps a different version of tensorboard should be installed?

**Comment by zihaolucky** [comment]
@taolei87 Sorry for my misunderstand this issue with the one in #36 

Seems it's a problem of virtual env and python2.7, so it might be hard to provide a solution for virtual env users quickly, but here's a possible solution for this https://github.com/QQuick/Transcrypt/issues/13. 

BTW, the `site.getsitepackages()` here is a trick to find the `/tensorboard/tensorboard.runfiles`, so I think if you could find the `.runfiles`, directly return its location might do the trick. Just change the code in `/Users/taolei/dlenv/bin/tensorboard`, change it to the correct location:

```python
  64 # Find the runfiles tree
  65 def FindModuleSpace():
  66   # Follow symlinks, looking for my module space
  67   stub_filename = os.path.abspath(sys.argv[0])
  68   while True:
  69     # Found it?
  70     module_space = stub_filename + '.runfiles'
  71     if os.path.isdir(module_space):
  72       break
  73     package_path = site.getsitepackages()
  74     # In case this instance is a string
  75     if not isinstance(package_path, list):
  76       package_path = [package_path]
  77     user_path = site.getusersitepackages()
  78     if not isinstance(user_path, list):
  79       user_path = [user_path]
  80     package_path.extend(user_path)
  81     for mod in package_path:
  82       module_space = mod + '/tensorboard/tensorboard' + '.runfiles'
  83       if os.path.isdir(module_space):
  84         return module_space
```

**Comment by taolei87** [comment]
@zihaolucky directly returning the .runfiles worked. thanks a lot!

**Comment by zihaolucky** [comment]
Glad to help, if you have a better solution for both VirtualEnv and Anaconda, just submit a PR.

**Comment by nathanin** [comment]
Before this I had no idea what .runfiles were.

For others like me who may find this issue, I inserted the path: `~/Envs/tensorflow/lib/python2.7/site-packages/tensorboard/tensorboard.runfiles` and it appears to work.

**Comment by jowettcz** [comment]
@zihaolucky  @nathanin thanks for you reminder. I also fixed the problem by show the  exact location of tensorboard.runfiles.

**Comment by mahtorohit** [comment]
worked just fine, Just commented the runfiles search code by returning hardcoded path 
env/bin/tensorboard/tensorboard.runfiles
    ```
    # for mod in site.getsitepackages():
    #   module_space = mod + '/tensorboard/tensorboard' + '.runfiles'
    #   if os.path.isdir(module_space):
    #     return module_space

    return "XXX/env/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles"
```

**Comment by Erotemic** [comment]
Not sure why this issue is closed. This issue effects me in python3.5 with virtualenv.

Note a more general fix would be to replace line 69 with 

```python
    if hasattr(site, 'getsitepackages'):
        # normal execution
        sitepackages = site.getsitepackages()
    else:
        # workaround for virtualenv
        from distutils.sysconfig import get_python_lib
        sitepackages = [get_python_lib()]
    for mod in sitepackages:
```

I would submit a PR, but having to go through legal hoops to do so really kills my motivation. I'm likely just not going to do it. So, perhaps someone who feels like filling out paperwork can patch this in.

In case it helps: I wave all rights to the above code, anybody can use it however he or she wants under the [WTFPL](http://www.wtfpl.net/) Licence Version 2. However, I'd be really happy if I could pip install tensorboard without having to patch a file, so hopefully this patch can be applied.

**Comment by zihaolucky** [comment]
@Erotemic Thanks for your contribution!

I suppose we've settled a new PyPI repo with TensorBoard dev team, as one of their team member reached me a couple weeks ago said we can use `dmlc-tensorboard`. The point is about the name of PyPI, not on the project or the scope we're going to do.

**Comment by Erotemic** [comment]
Oh, I didn't realize this wasn't the official tensorboard. I'm currently using pytorch, so I find this project very useful.

**Comment by Davidrjx** [comment]
is there a general solution for getsitepackages and getusersitepackages in tensorboard binary script ?
