### ISSUE TITLE
How to install the tensorboard server?

### ISSUE THREAD

**Issue by botev** [dmlc/tensorboard#40]
Hi,

I was assuming that when I've installed through PyPI the tensorboard it will also install the tensorboard server app. However, is this correct? Currently I get:
```
$tensorboard --logdir=logs
Traceback (most recent call last):
  File "/opt/anaconda3/bin/tensorboard", line 160, in <module>
    Main()
  File "/opt/anaconda3/bin/tensorboard", line 110, in Main
    module_space = FindModuleSpace()
  File "/opt/anaconda3/bin/tensorboard", line 91, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for /opt/anaconda3/bin/tensorboard
```
This is on Ubuntu 16.04 with Anaconda 4.2.13 and python 3.6

**Comment by zihaolucky** [comment]
Yes, but the latest version `1.0.0a7` is broken, I've remote this release and now `1.0.0a6` should be okay. Could you try again? `pip uninstall tensorboard` then `pip install tensorboard`

**Comment by botev** [comment]
That almost fixed it you have a few issues with python3:

1. In `tensorboard/summary.py` line 39 change `impoet StringIO` to `from io import StringIO`
2. In `tensorboard/event_file_writer.py` line 69 change `file_prefix` to `file_prefix.decode()`

You might actually want to do these with actual checks of the python versions.
