### ISSUE TITLE
Error mx.tensorboard

### ISSUE THREAD

**Issue by Shiro-mx** [dmlc/tensorboard#44]
Hello,

I have an error I do not succeed to solve. 

```
batch_end_callbacks = [mx.tensorboard.LogMetricsCallback(training_log)] 
AttributeError: 'module' object has no attribute 'tensorboard'
```
I installed tensorboard with pip and it seems to work when I call tensor board alone. But when I want to use it with mxnet, it gives me this error. Does someone have an idea to solve this problem ?

Thanks for the help !

**Comment by zihaolucky** [comment]
The tensorboard plugin is in https://github.com/dmlc/mxnet/blob/master/python/mxnet/contrib/tensorboard.py. You may want to use `mx.contrib.tensorboard`.

**Comment by Shiro-mx** [comment]
it works well, thank you !
