### ISSUE TITLE
PyPI tensorboard-1.0.0a6 version not available for Python 3.6 on Linux (only for Python 3.5)

### ISSUE THREAD

**Issue by tdomhan** [dmlc/tensorboard#45]
Hi!
we noticed that when installing tensorboard through pip there is no version 1.0.0a6 for python 3.6 on Linux (there is only a version of Mac Os X). It would be great if you could upload a manylinux version for python 3.6 as well.

Thanks in advance,
Tobi

**Comment by tdomhan** [comment]
any updates on this issue? :)

**Comment by zihaolucky** [comment]
@tdomhan I restart the travis job here https://travis-ci.org/zihaolucky/tensorboard-distro/jobs/211231491

**Comment by tdomhan** [comment]
great thanks!

**Comment by zihaolucky** [comment]
@tdomhan It's ok now. Have a nice day.
