### ISSUE TITLE
Unable to build with sources

### ISSUE THREAD

**Issue by jihunchoi** [dmlc/tensorboard#48]
Hi, I am really enjoy using the standalone tensorboard tool!
However, I found that the latest master branch of the tensorflow library does not contain "tensorflow/tensorboard", thus when I run "installer.sh", it fails to compile.

~~Since the master branch is quite unstable and prone to change, I suggest that cloning a specific stable version of tensorflow instead of the latest version.
Say the stable version is r1.2, it could be easily fixed by changing the line
`git clone https://github.com/tensorflow/tensorflow`
with
`git clone -b r1.2 https://github.com/tensorflow/tensorflow`.~~

Seeing the situation again, it seems that the separation of tensorboard from tensorflow is permanant, thus it'd be better fixing the installation script to run with the separated tensorboard repo.

**Comment by zihaolucky** [comment]
@jihunchoi Thanks for your report. Please refer the code here https://github.com/zihaolucky/tensorboard-distro/blob/master/travis_installer.sh#L14-L18 to resolve your issue.

I'm going to change the backend to tensorflow/tensorboard and change our project name to `tensorboard-lite` once we finish the refactor, the interface won't change.

**Comment by zihaolucky** [comment]
@jihunchoi I've updated the script yesterday, can you build it from source now?
