### ISSUE TITLE
Tensorboard SummaryWriter

### ISSUE THREAD

**Issue by akhilesh-pandey** [dmlc/tensorboard#62]
I am trying to run one code that I forked from [here](https://github.com/xmfbit/captcha-recognition). This uses tensorboard as given in the following line:
`logger = tensorboard.SummaryWriter('./log')`
This throws an error saying :

>  AttributeError: module 'tensorboard' has no attribute 'SummaryWriter'

Any suggestions what should I do next?

**Comment by zihaolucky** [comment]
@akhilesh-pandey I suggest https://github.com/awslabs/mxboard, the usage is quite similar. But make sure you have install mxboard or dmlc/tensorboard first.
