### ISSUE TITLE
sh installer.sh  failed

### ISSUE THREAD

**Issue by austingg** [dmlc/tensorboard#9]
hi, guys
I am trying to test the tutorial. However, when i run `sh installer.sh`, an error ocurred
```shell
INFO: Elapsed time: 366.295s, Critical Path: 291.77s
sh: bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh: No such  or directory
Requirement 'python/dist/*.whl' looks like a filename, but the file does exist
*.whl is not a valid wheel filename.
Now you can remove tensorflow with rm -rf tensorflow
```
System Version: CentOS 7.1

**Comment by zihaolucky** [comment]
Seems https://github.com/dmlc/tensorboard/blob/master/installer.sh#L18 do the trick. I forgot to change this with `tools/pip_package/build_pip_package.sh`

**Comment by austingg** [comment]
Thanks a lot. 
you have copyed 'tools' directory rescursively, so the path should be inserted a 'tools'.
After I did that, the whl is built successfully. However, when i run the mnist tutorial, it says `no module named src.summary_pb2` when importing tensorboard summary

**Comment by zihaolucky** [comment]
Could you please list your dir and files under `python/tensorboard` and `python/tensorboard/src`? 

I would try to reproduce this.

**Comment by zihaolucky** [comment]
```
INFO: Elapsed time: 1753.574s, Critical Path: 1239.63s
2017年 1月 9日 星期一 19时13分55秒 CST : === Using tmpdir: ../python/tensorboard/
Really old (0.2.1-) runfiles, without workspace name
~/Workspace/tensorboard/python/tensorboard ~/Workspace/tensorboard/tensorflow
2017年 1月 9日 星期一 19时13分55秒 CST : === Building wheel
warning: no files found matching '*.csv' under directory '*'
2017年 1月 9日 星期一 19时14分19秒 CST : === Output wheel file is in: ../python/dist/
Processing ./python/dist/tensorboard-0.12.0rc1-cp27-cp27m-macosx_10_6_x86_64.whl
Requirement already satisfied: mock>=2.0.0 in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from tensorboard==0.12.0rc1)
Requirement already satisfied: six>=1.10.0 in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from tensorboard==0.12.0rc1)
Requirement already satisfied: numpy>=1.11.0 in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from tensorboard==0.12.0rc1)
Requirement already satisfied: protobuf>=3.1.0 in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from tensorboard==0.12.0rc1)
Requirement already satisfied: wheel in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from tensorboard==0.12.0rc1)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from mock>=2.0.0->tensorboard==0.12.0rc1)
Requirement already satisfied: pbr>=0.11 in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from mock>=2.0.0->tensorboard==0.12.0rc1)
Requirement already satisfied: setuptools in /Users/zihao.zzh/anaconda2/envs/tensorboard/lib/python2.7/site-packages (from protobuf>=3.1.0->tensorboard==0.12.0rc1)
Installing collected packages: tensorboard
Successfully installed tensorboard-0.12.0rc1
Now you can remove tensorflow with rm -rf tensorflow
```

The installer works fine in my Mac. I would test this in Linux later.

**Comment by austingg** [comment]
yes , these are src/summary_pb2.py, in the python/tensorboard/src. 
I have done a clean-up build, and successed to install the tensorboard. 
Thanks a lot.

**Comment by zihaolucky** [comment]
Yep, congrats!

**Comment by zihaolucky** [comment]
@austingg To ensure again, are you successfully install tensorboard with the `installer.sh`, without any other work? I mean, the script is correct.

**Comment by austingg** [comment]
No, I fixed the bazel-bin/tensorflow/tools/**tools**/pip-xxxxxxxxx with **tools** inserted.
besides, there is no train_model_monitor.py in the doc/tutorial/ directory. Seems it is unnecessary.

**Comment by zihaolucky** [comment]
Could you submit a PR to fix this? But it's weird it works fine on Mac.

**Comment by austingg** [comment]
I found it maybe caused by the tiny difference of `cp -r` between Mac and CentOS. I have tested on Mac, the `cp -r tools/` just copy the subdirectory of tools/, while on CentOS, it copys the tools as well

**Comment by austingg** [comment]
we can fix that like 
` cp -r tools/* ......` 
both works on Mac and CentOS, you may have a try.

**Comment by zihaolucky** [comment]
@austingg Yes, thank you~
